openapi: 3.0.3
info:
  title: Pricing Service API
  description: API for retrieving and managing pricing details for Dave's Pet Shop.
  version: 1.0.0
servers:
  - url: https://api.davespetshop.com/v1
    description: Production server
  - url: https://staging.api.davespetshop.com/v1
    description: Staging server

paths:
  /prices:
    get:
      summary: Get current prices for all products
      tags:
        - Prices
      responses:
        '200':
          description: A list of current product prices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductPrice'

  /prices/{productId}:
    get:
      summary: Get the current price for a specific product
      tags:
        - Prices
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            description: The ID of the product
      responses:
        '200':
          description: The current price for the specified product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPrice'
        '404':
          description: Product not found

  /prices/historical:
    get:
      summary: Get historical pricing for a specific product
      tags:
        - Prices
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: string
            description: The ID of the product
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
            description: The start date for the historical data (YYYY-MM-DD)
        - name: endDate
          in: query
          required: false
          schema:
            type: string
            format: date
            description: The end date for the historical data (YYYY-MM-DD)
      responses:
        '200':
          description: A list of historical prices for the specified product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoricalProductPrice'
        '400':
          description: Invalid date range
        '404':
          description: Product not found

  /prices/bulk:
    post:
      summary: Get prices for multiple products
      tags:
        - Prices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkPriceRequest'
      responses:
        '200':
          description: List of prices for the requested products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductPrice'
        '400':
          description: Invalid request parameters

  /prices/supported-products:
    get:
      summary: Get a list of all products with pricing information
      tags:
        - Prices
      responses:
        '200':
          description: A list of product IDs with pricing information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Product ID
        '500':
          description: Internal server error

components:
  schemas:
    ProductPrice:
      type: object
      properties:
        productId:
          type: string
          description: The unique identifier for the product
        productName:
          type: string
          description: The name of the product
        price:
          type: number
          format: float
          description: The current price of the product
        currency:
          type: string
          description: The currency of the price (e.g., USD)
        lastUpdated:
          type: string
          format: date-time
          description: The timestamp of when the price was last updated

    HistoricalProductPrice:
      type: object
      properties:
        date:
          type: string
          format: date
          description: The date of the historical price
        price:
          type: number
          format: float
          description: The price of the product on that date
        currency:
          type: string
          description: The currency of the price (e.g., USD)

    BulkPriceRequest:
      type: object
      properties:
        productIds:
          type: array
          items:
            type: string
          description: A list of product IDs for which prices are requested
